module MemoryApp {

typedef sequence<string> mArray;
 
	interface Memory {
	 
		boolean login(in string name, in string password);
		void register(in string username, in string password);
		void addMemory(in string memory);
		void addResource(in string resource, in string memory);
		void deleteResource(in string resource);
		void shareMemory(in string memory, in string username);
		void transferPoints(in long points, in string username);
		string getUser();
		long getUserID();
		void deleteMemory(in string memory);
		string viewMemories();
		void sendInvite(in string friendUserName);
		boolean viewInvites(); 
		string viewInviteSender();
		void acceptInvite();
		long viewPoints();
		}; 
	};