package MemoryApp;


/**
* MemoryApp/_MemoryImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from memory.idl
* 27 November 2014 13:59:33 o'clock GMT
*/

public abstract class _MemoryImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MemoryApp.Memory, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MemoryImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("register", new java.lang.Integer (1));
    _methods.put ("addMemory", new java.lang.Integer (2));
    _methods.put ("addResource", new java.lang.Integer (3));
    _methods.put ("getUser", new java.lang.Integer (4));
    _methods.put ("deleteMemory", new java.lang.Integer (5));
    _methods.put ("viewMemories", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MemoryApp/Memory/login
       {
         String name = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.login (name, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MemoryApp/Memory/register
       {
         String username = in.read_string ();
         String password = in.read_string ();
         this.register (username, password);
         out = $rh.createReply();
         break;
       }

       case 2:  // MemoryApp/Memory/addMemory
       {
         String memory = in.read_string ();
         this.addMemory (memory);
         out = $rh.createReply();
         break;
       }

       case 3:  // MemoryApp/Memory/addResource
       {
         String resource = in.read_string ();
         String memory = in.read_string ();
         this.addResource (resource, memory);
         out = $rh.createReply();
         break;
       }

       case 4:  // MemoryApp/Memory/getUser
       {
         String $result = null;
         $result = this.getUser ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MemoryApp/Memory/deleteMemory
       {
         String memory = in.read_string ();
         this.deleteMemory (memory);
         out = $rh.createReply();
         break;
       }

       case 6:  // MemoryApp/Memory/viewMemories
       {
         String $result = null;
         $result = this.viewMemories ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MemoryApp/Memory:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _MemoryImplBase
