package MemoryApp;


/**
* MemoryApp/MemoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from memory.idl
* 28 November 2014 14:06:36 o'clock GMT
*/

public interface MemoryOperations 
{
  boolean login (String name, String password);
  void register (String username, String password);
  void addMemory (String memory);
  void addResource (String resource, String memory);
  String getUser ();
  int getUserID ();
  void deleteMemory (String memory);
  String viewMemories ();
  void sendInvite (String friendUserName);
  boolean viewInvites ();
  String viewInviteSender ();
  void acceptInvite ();
  int viewPoints ();
} // interface MemoryOperations
