package MemoryApp;


/**
* MemoryApp/MemoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from memory.idl
* 27 November 2014 13:59:33 o'clock GMT
*/

public interface MemoryOperations 
{
  boolean login (String name, String password);
  void register (String username, String password);
  void addMemory (String memory);
  void addResource (String resource, String memory);
  String getUser ();
  void deleteMemory (String memory);
  String viewMemories ();
} // interface MemoryOperations
