package MemoryApp;


/**
* MemoryApp/Memory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Memory.idl
* 18 November 2014 20:01:41 o'clock GMT
*/

public interface Memory extends MemoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Memory
