package MemoryApp;


/**
* MemoryApp/MemoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Memory.idl
* 13 December 2014 17:46:42 o'clock GMT
*/

public interface MemoryOperations 
{
  boolean login (String name, String password);
  void register (String username, String password);
  void addMemory (String memory);
  void addResource (String resource, String memory);
  void deleteResource (String resource);
  void shareMemory (String memory, String username);
  void transferPoints (int points, String username);
  String getUser ();
  int getUserID ();
  void deleteMemory (String memory);
  String viewMemories ();
  void sendInvite (String friendUserName);
  boolean viewInvites ();
  String viewInviteSender ();
  void acceptInvite ();
  int viewPoints ();
} // interface MemoryOperations
