package MemoryApp;


/**
* MemoryApp/Memory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from memory.idl
* 28 November 2014 14:06:36 o'clock GMT
*/

public interface Memory extends MemoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Memory
