package MemoryApp;


/**
* MemoryApp/Memory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Memory.idl
* 13 December 2014 17:46:42 o'clock GMT
*/

public interface Memory extends MemoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Memory
